import http from "http";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = process.env.PORT || 3001;
const ORDERS_FILE = path.join(__dirname, "orders.json");
const DIST_DIR = path.join(__dirname, "dist");

let orders = [];
if (fs.existsSync(ORDERS_FILE)) {
  try {
      orders = JSON.parse(fs.readFileSync(ORDERS_FILE, "utf-8"));
          console.log(`Loaded ${orders.length} existing order(s) from disk.`);
            } catch {
                orders = [];
                  }
                  }

                  function persist() {
                    try { fs.writeFileSync(ORDERS_FILE, JSON.stringify(orders, null, 2)); }
                      catch (e) { console.warn("Could not persist orders:", e.message); }
                      }

                      function uid() {
                        return Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
                        }

                        function setCors(res) {
                          res.setHeader("Access-Control-Allow-Origin", "*");
                            res.setHeader("Access-Control-Allow-Methods", "GET, POST, PATCH, DELETE, OPTIONS");
                              res.setHeader("Access-Control-Allow-Headers", "Content-Type");
                              }

                              function readBody(req) {
                                return new Promise((resolve, reject) => {
                                    let data = "";
                                        req.on("data", (chunk) => (data += chunk));
                                            req.on("end", () => {
                                                  try { resolve(data ? JSON.parse(data) : {}); }
                                                        catch (e) { reject(e); }
                                                            });
                                                              });
                                                              }

                                                              const MIME = {
                                                                ".html": "text/html",
                                                                  ".js": "application/javascript",
                                                                    ".css": "text/css",
                                                                      ".png": "image/png",
                                                                        ".jpg": "image/jpeg",
                                                                          ".jpeg": "image/jpeg",
                                                                            ".svg": "image/svg+xml",
                                                                              ".ico": "image/x-icon",
                                                                                ".json": "application/json",
                                                                                  ".woff": "font/woff",
                                                                                    ".woff2": "font/woff2",
                                                                                      ".ttf": "font/ttf",
                                                                                        ".webp": "image/webp",
                                                                                        };

                                                                                        function serveStatic(req, res) {
                                                                                          let filePath = path.join(DIST_DIR, req.url === "/" ? "index.html" : req.url);
                                                                                            filePath = filePath.split("?")[0];
                                                                                              if (!fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) {
                                                                                                  filePath = path.join(DIST_DIR, "index.html");
                                                                                                    }
                                                                                                      const ext = path.extname(filePath).toLowerCase();
                                                                                                        const mimeType = MIME[ext] || "application/octet-stream";
                                                                                                          fs.readFile(filePath, (err, data) => {
                                                                                                              if (err) {
                                                                                                                    res.writeHead(404, { "Content-Type": "text/plain" });
                                                                                                                          res.end("Not found");
                                                                                                                                return;
                                                                                                                                    }
                                                                                                                                        res.writeHead(200, { "Content-Type": mimeType });
                                                                                                                                            res.end(data);
                                                                                                                                              });
                                                                                                                                              }
                                                                                                                                              
                                                                                                                                              const server = http.createServer(async (req, res) => {
                                                                                                                                                setCors(res);
                                                                                                                                                  const url = req.url.split("?")[0];
                                                                                                                                                    if (req.method === "OPTIONS") {
                                                                                                                                                        res.writeHead(204);
                                                                                                                                                            return res.end();
                                                                                                                                                              }
                                                                                                                                                                if (url.startsWith("/api/")) {
                                                                                                                                                                    res.setHeader("Content-Type", "application/json");
                                                                                                                                                                        if (req.method === "POST" && url === "/api/orders") {
                                                                                                                                                                              try {
                                                                                                                                                                                      const body = await readBody(req);
                                                                                                                                                                                              const order = {
                                                                                                                                                                                                        id: uid(),
                                                                                                                                                                                                                  tableNumber: body.tableNumber,
                                                                                                                                                                                                                            items: body.items,
                                                                                                                                                                                                                                      total: body.total,
                                                                                                                                                                                                                                                note: body.note || "",
                                                                                                                                                                                                                                                          status: "pending",
                                                                                                                                                                                                                                                                    createdAt: new Date().toISOString(),
                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                    orders.unshift(order);
                                                                                                                                                                                                                                                                                            persist();
                                                                                                                                                                                                                                                                                                    console.log(`New order - Table ${order.tableNumber} Rs${order.total}`);
                                                                                                                                                                                                                                                                                                            res.writeHead(201);
                                                                                                                                                                                                                                                                                                                    res.end(JSON.stringify(order));
                                                                                                                                                                                                                                                                                                                          } catch {
                                                                                                                                                                                                                                                                                                                                  res.writeHead(400);
                                                                                                                                                                                                                                                                                                                                          res.end(JSON.stringify({ error: "Bad request" }));
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                              if (req.method === "GET" && url === "/api/orders") {
                                                                                                                                                                                                                                                                                                                                                                    res.writeHead(200);
                                                                                                                                                                                                                                                                                                                                                                          res.end(JSON.stringify(orders));
                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                        const patchMatch = url.match(/^\/api\/orders\/([^/]+)$/);
                                                                                                                                                                                                                                                                                                                                                                                            if (req.method === "PATCH" && patchMatch) {
                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                          const id = patchMatch[1];
                                                                                                                                                                                                                                                                                                                                                                                                                  const body = await readBody(req);
                                                                                                                                                                                                                                                                                                                                                                                                                          const order = orders.find((o) => o.id === id);
                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!order) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            res.writeHead(404);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      return res.end(JSON.stringify({ error: "Order not found" }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      order.status = body.status || order.status;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              order.updatedAt = new Date().toISOString();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      persist();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.writeHead(200);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.end(JSON.stringify(order));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.writeHead(400);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.end(JSON.stringify({ error: "Bad request" }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (req.method === "DELETE" && url === "/api/orders") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      orders = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            persist();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.writeHead(200);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.end(JSON.stringify({ ok: true }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.writeHead(404);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.end(JSON.stringify({ error: "Not found" }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  serveStatic(req, res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  server.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`Boston Cafe - Server running on port ${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
